### ISSUE TITLE
feature: download progress tracking

### ISSUE THREAD

**Issue by lrstanley** [lrstanley/go-ytdlp#27]
### ✨ Describe the feature you'd like

Progress hook function, which both applies the necessary CLI flags to yt-dlp to track progress, and allows providing a callback to receive progress updates.

- ref: https://github.com/lrstanley/go-ytdlp/pull/16#issuecomment-2235253599
- ref: https://github.com/eos175/go-ytdlp/commit/8eb98f3a3b4af4d47306589303402654cd00c859#diff-4d7d1923693fc5ce892add2ea2907a744e77ea0b50c1939ccc5067cb48a466a3

Would like to ensure:
- It uses the builder approach
- Uses callback approach
- Does not prevent json output
- Tracks:
  - bytes downloaded
  - total bytes
  - progress status
  - low priority: speed
  - low priority: ETA

We could calculate some of the info ourselves (speed, ETA).

### 🔎 Describe alternatives you've considered

n/a

### ⚠ If implemented, do you think this feature will be a breaking change to users?

No

### 🤝 Requirements

- [X] I have confirmed that someone else has not [submitted a similar feature request](../labels/enhancement).
- [X] If implemented, I believe this feature will help others, in addition to solving my problems.
- [X] I have looked into alternative solutions to the best of my ability.
- [X] (optional) I would be willing to contribute to testing this feature if implemented, or making a PR to implement this functionality.

**Comment by eos175** [comment]
The json output remains unaffected in the latest version.

I prefer simplicity, hence the callback only receives `totalBytes, downloadedBytes`. With these, eta, speed, progress bars can be easily calculated. Sending fewer details to yt-dlp is preferable, in my opinion. The missing piece is `progress_status`.

```go
SetProgress(500*time.Millisecond, func(totalBytes, downloadedBytes int) {
	percentage := (float64(downloadedBytes) / float64(totalBytes)) * 100
	remainingBytes := totalBytes - downloadedBytes

	fmt.Printf("Progress: %.2f%% (%d/%d bytes), Remaining: %d bytes\n", percentage, downloadedBytes, totalBytes, remainingBytes)
})
```

Another thing is that for some reason, we don't always have the `totalBytes`, and without it, we can't calculate `eta`.

**Comment by eos175** [comment]
Currently, I am using the following [commit](https://github.com/eos175/go-ytdlp/commit/57adbd1c3422efd7eec1c616a6fcb60fc557ab6e)
I use it as follows:

```go
dl := ytdlp.New().
	PrintJSON().
	Format("251").
	Output("%(extractor)s - %(title)s.%(ext)s").
	SetProgress(100*time.Millisecond, func(totalBytes, downloadedBytes int, status string) {
		if totalBytes == 0 {
			fmt.Printf("Progress (%s): %d bytes downloaded, total size unknown\n", status, downloadedBytes)
		} else {
			percentage := (float64(downloadedBytes) / float64(totalBytes)) * 100
			remainingBytes := totalBytes - downloadedBytes
			fmt.Printf("Progress (%s): %.2f%% (%d/%d bytes), Remaining: %d bytes\n", status, percentage, downloadedBytes, totalBytes, remainingBytes)
		}
	})
res, err := dl.Run(context.TODO(), "https://www.youtube.com/watch?v=dQw4w9WgXcQ")
if err != nil {
	panic(err)
}
```

There is JSON output and a progress bar. If a `Format` is not specified, `ytdlp` downloads `video only` + `audio only`, so the log will look something like this because there are two downloads and then `ffmpeg` merges audio and video:

```
Progress (downloading): 100.00% (90517566/90517566 bytes), Remaining: 0 bytes
Progress (downloading): 100.00% (91557950/91557950 bytes), Remaining: 0 bytes
Progress (downloading): 100.00% (92289012/92289012 bytes), Remaining: 0 bytes
Progress (finished): 100.00% (92289012/92289012 bytes), Remaining: 0 bytes
Progress (downloading): 0.03% (1024/3437753 bytes), Remaining: 3436729 bytes
Progress (downloading): 15.22% (523264/3437753 bytes), Remaining: 2914489 bytes
Progress (downloading): 60.97% (2096128/3437753 bytes), Remaining: 1341625 bytes
Progress (downloading): 100.00% (3437753/3437753 bytes), Remaining: 0 bytes
Progress (finished): 100.00% (3437753/3437753 bytes), Remaining: 0 bytes
```
